export enum ENVEnum {
  NODE_ENV = 'NODE_ENV',
  DATABASE_URL = 'DATABASE_URL',

  PORT = 'PORT',
  BASE_URL = 'BASE_URL',

  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRES_IN = 'JWT_EXPIRES_IN',
  REFRESH_TOKEN_LENGTH = 'REFRESH_TOKEN_LENGTH',
  REFRESH_TOKEN_EXPIRES_DAYS = 'REFRESH_TOKEN_EXPIRES_DAYS',

  MAIL_USER = 'MAIL_USER',
  MAIL_PASS = 'MAIL_PASS',
  MAIL_PORT = 'MAIL_PORT',
  MAIL_HOST = 'MAIL_HOST',

  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',

  SUPER_ADMIN_EMAIL = 'SUPER_ADMIN_EMAIL',
  SUPER_ADMIN_PASS = 'SUPER_ADMIN_PASS',

  AWS_REGION = 'AWS_REGION',
  AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID',
  AWS_SECRET_ACCESS_KEY = 'AWS_SECRET_ACCESS_KEY',
  AWS_S3_BUCKET_NAME = 'AWS_S3_BUCKET_NAME',

  // Rate Limiting
  THROTTLE_TTL = 'THROTTLE_TTL',
  THROTTLE_LIMIT = 'THROTTLE_LIMIT',

  // Auth-specific rate limits
  LOGIN_MAX_ATTEMPTS = 'LOGIN_MAX_ATTEMPTS',
  LOGIN_WINDOW_MS = 'LOGIN_WINDOW_MS',
  SIGNUP_MAX_ATTEMPTS = 'SIGNUP_MAX_ATTEMPTS',
  SIGNUP_WINDOW_MS = 'SIGNUP_WINDOW_MS',
  OTP_MAX_ATTEMPTS = 'OTP_MAX_ATTEMPTS',
  OTP_WINDOW_MS = 'OTP_WINDOW_MS',
  PASSWORD_RESET_MAX_ATTEMPTS = 'PASSWORD_RESET_MAX_ATTEMPTS',
  PASSWORD_RESET_WINDOW_MS = 'PASSWORD_RESET_WINDOW_MS',

  // Twilio
  TWILIO_ACCOUNT_SID = 'TWILIO_ACCOUNT_SID',
  TWILIO_AUTH_TOKEN = 'TWILIO_AUTH_TOKEN',
  TWILIO_PHONE_NUMBER = 'TWILIO_PHONE_NUMBER',
  logo_URL = 'LOGO_URL',

  // Stripe
  STRIPE_SECRET_KEY = 'STRIPE_SECRET_KEY',
  STRIPE_WEBHOOK_SECRET = 'STRIPE_WEBHOOK_SECRET',
  STRIPE_PUBLIC_KEY = 'STRIPE_PUBLIC_KEY',

  // AI integration
  AI_SPACE_OPTIMIZATION_URL = 'AI_SPACE_OPTIMIZATION_URL',

  // Frontend URL
  FRONTEND_URL = 'FRONTEND_URL',
}
